apiVersion: v1
kind: Service
metadata:
  name: chat-gpt-clone-app
  labels:
    app: chat-gpt-clone-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  externalIPs:
  - 192.168.68.87
  selector:
    app: chat-gpt-clone-app
